FROM debian:latest
RUN apt-get update && apt-get -y install curl 
CMD ["sleep", "infinity"]

# docker run -d --name debian-sleep thegeekspad/debian-infinite-sleep
# docker exec debian-sleep curl microsoft.com -v
# docker exec -it debian-sleep bash
# docker stop debian-sleep
# docker rm debian-sleep
# docker rmi thegeekspad/debian-infinite-sleep
